### ISSUE TITLE
start and interact with monero-wallet-rpc inside swapd

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#168]
credits to @dimalinux for this idea!

instead of having the user/scripts start and run monero-wallet-rpc and create/open wallets, we can have swapd handle starting the process and create/open wallets as needed.

**Comment by dimalinux** [comment]
I did testing to understand nuances of `monero-wallet-rpc`'s behavior. It can take `--wallet-dir` or `--wallet-file`, but it won't allow you to pass both flags together. `--wallet-file`'s value must be a path to the wallet file, which follows from the fact that you can't combine the two flags. If you start `monero-wallet-rpc` with `--wallet-file`, then invoke `close_wallet`, `create_wallet` and `open_wallet` RPC operations on same `monero-wallet-rpc` instance behave as if you had passed `--wallet-dir` with the directory that the initially opened wallet was in.

I've been trying to brainstorm what might be the simplest, but functional, user interface. My current best idea is:
* Have `swapd` only take a `--wallet-file` argument (no need to support `--wallet-dir`).
* If not passed, the wallet file will default to `$HOME/.atomicswap/{ENV}/wallet/swap-wallet`.
* If the wallet file is not present, we'll automatically create it.
* We'll create temporary swap wallets in the same directory as the wallet passed to `swapd`'s `--wallet-file` flag.
* `swapd` will provide an RPC API to get the balance of the monero wallet (and ethereum for symmetry) and also display a public address for each so the user knows what wallet has the balance. We don't expect the user to query the `monero-wallet-rpc` instance that we internally start on a randomized port for balances.
* `swapcli` willl be extended with a `balance` subcommand.
