### ISSUE TITLE
Offer taken off offers list on invalid incoming take

### ISSUE THREAD

**Issue by doonte** [AthanorLabs/atomic-swap#172]
A taker who sends an invalid take of an offer (for example, provided amount too low) will still cause the offer to be removed from the xmr maker's offer list, despite the take offer not being valid. Other peers will not be able to try to take the same offer since it is gone.

To reproduce:
- Create maker and taker1 and taker2
- maker creates an offer
- taker1 takes the offer but with provided amount too low
- taker2 tries to take the same offer, but it no longer exists

**Comment by noot** [comment]
interesting, the code here is supposed to prevent this from happening, as it re-adds the offer back if the swap fails: https://github.com/AthanorLabs/atomic-swap/blob/master/protocol/xmrmaker/swap_state.go#L187

what method were you using to get this to happen? was it manual CLI testing or something else?

**Comment by doonte** [comment]
I am using manual CLI testing. I don't think it ever got to the `exit` function, it fails at `net/initiate.go` at `h.handler.HandleInitiateMessage(im)` before the `initiate` call is made setting up the swap state.

First, set up everything. Then, create a make offer
```bash
curl -X POST http://127.0.0.1:5002 -d '{"jsonrpc":"2.0","id":"0","method":"net_makeOffer","params":{"minimumAmount":1, "maximumAmount":10, "exchangeRate": 0.1}}' -H 'Content-Type: application/json'
# {"jsonrpc":"2.0","result":{"offerID":"102fbdd30756f9d10129e0cd80bd3c234e1541bf7c1d4017e3e224997898d1de","infoFile":"~/.atomicswap/dev/2022-08-25-03:10:38.688259186"},"id":"0"}
```

Try to take it with an amount too low
```bash
./swapcli take --multiaddr /ip4/127.0.0.1/tcp/9934/p2p/Lf1iM0Ils4l12nOitrxBPXSXWU9Oh4aMfGquN6y8a5tKL3xVtRa3 --offer-id 102fbdd30756f9d10129e0cd80bd3c234e1541bf7c1d4017e3e224997898d1de --provides-amount 0.04
# Initiated swap with ID 102fbdd30756f9d10129e0cd80bd3c234e1541bf7c1d4017e3e224997898d1de
```

xmrmaker will fail in `initiate.go`, xmrtaker will pause waiting for a reply it will never get.

Try to take it again, even with a valid provides amount:
```bash
./swapcli take --multiaddr /ip4/127.0.0.1/tcp/9934/p2p/Lf1iM0Ils4l12nOitrxBPXSXWU9Oh4aMfGquN6y8a5tKL3xVtRa3 --offer-id 102fbdd30756f9d10129e0cd80bd3c234e1541bf7c1d4017e3e224997898d1de --provides-amount 0.5
# 2022-08-25T03:18:07.199Z	ERROR	cmd	client/main.go:224	failed to call net_takeOffer: message=peer does not have offer with given ID; code=-32000; data=map[]
```
