### ISSUE TITLE
where to find out the roadmap or manual book of this atomic-swap mechanism

### ISSUE THREAD

**Issue by LBruyne** [AthanorLabs/atomic-swap#176]
I'd like to know where to find out the roadmap or manual book of this atomic-swap mechanism?
This can make a further understand for us.

**Comment by noot** [comment]
Hi @LBruyne , you can find the atomic swap protocol documented here: https://github.com/AthanorLabs/atomic-swap/blob/master/docs/eth-xmr-atomic-swaps.pdf

If you want to try running the code yourself, you can try the instructions here: https://github.com/AthanorLabs/atomic-swap/blob/master/docs/local.md

Let me know if you have further questions!

**Comment by noot** [comment]
closing for now, feel free to re-open if you have specific questions

**Comment by LBruyne** [comment]
Thank you!
