### ISSUE TITLE
deprecate `contract-addresses.json` 

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#202]
currently, if swapd deploys a swap contract (for testing purposes) it gets written to `contract-address.json`. however, this isn't really needed, as contract addresses used in swaps are stored in the swap info file.

**Comment by dimalinux** [comment]
Is this ticket still needed?  We removed the info file. In order to remove the contract-addresses.json file, we would need some kind of tool that could extract the values from the database. Our integration tests depend on the file.
