### ISSUE TITLE
Review all message types

### ISSUE THREAD

**Issue by dimalinux** [AthanorLabs/atomic-swap#274]
We should review all the message types, ensure that the JSON handling is harmonized with the rest of the codebase, and make sure we do proper input validation on all fields from peers.

**Comment by noot** [comment]
@dimalinux was this completed?

**Comment by dimalinux** [comment]
We've made headway, but there is still work.  We want to get validation annotations on to all serialized data structures. When we add them, we should also be reviewing whether additional checks, beyond what validation tags can accomplish, are being performed.
