### ISSUE TITLE
better error handling of invalid offers loaded from DB on start

### ISSUE THREAD

**Issue by dimalinux** [AthanorLabs/atomic-swap#277]
The offer syntax may change from time to time and we might legitimately not want to support a legacy syntax. `swapd` should not exit on start if it encounters an offer in the database that is not valid:
https://github.com/AthanorLabs/atomic-swap/blob/1e83673f2398a6f2ae8b5611926a0a74d06480e6/db/database.go#L119-L122

We should log some information. I think these are only offers that haven't been taken and we can safely prune the bad ones from the database. @noot, is that correct?

**Comment by noot** [comment]
@dimalinux yep, I think if it finds an offer it can't load, it should just remove it from the db, and maybe log a warning.
