### ISSUE TITLE
Need lower bound on minimum XMR offer

### ISSUE THREAD

**Issue by dimalinux** [AthanorLabs/atomic-swap#286]
If the XMR amount in a swap is too low, there are insufficient funds to pay the fees to transfer the claimed or refunded funds from the swap wallet back to the primary address. We could avoid support questions if we just have a good error message early when the offer is created, that a min offer amount less than `X` XMR is not allowed.

I'm not sure how to come up with the ideal minimum value. Maybe someone reading this has ideas. My initial idea is 0.001 XMR ($0.20 if XMR is at $200 USD). Average fees appear to be around 0.0002 XMR (note the extra zero).

**Comment by noot** [comment]
this might be fixed by  #438
