### ISSUE TITLE
record peer IDs in swap info

### ISSUE THREAD

**Issue by dimalinux** [AthanorLabs/atomic-swap#299]
We should probably start recording peer IDs in the swap info database entries. A changed peer ID on either end after a swap is accepted up until the XMR locked notification will prohibit the swap from working.  Takers, who have potential gas to lose, probably want that history information as well. They can use that history information to give reliable makers repeat business.

**Comment by noot** [comment]
what do you mean "A changed peer ID on either end after a swap is accepted"? do you mean if the peer ID changes mid swap, or do you mean if the node goes offline?

**Comment by dimalinux** [comment]
If the peer ID changes mid-swap. It's not likely to happen if people use the default file locations, but if someone is explicitly using the `--libp2p-key` flag, it could easily happen if their swapd instance gets restarted in the middle of a swap.

**Comment by noot** [comment]
if the peer ID changes, the connection will end, and thus the counterparty node would try to end the swap asap, depending what stage they at. it's effectively the same as if the remote party disconnects, which is already handled

**Comment by doonte** [comment]
I don't think a non-random/constant peer ID could be used for reputation or history without impacting privacy. If the peer ID isn't random on every swap it could allow analysis entities to easily connect multiple trades (e.g., multiple XMR to ETH swaps to fresh addresses) to the same user and then de-anonymize them and the Ethereum addresses associated.

Even if we limit sharing a non-random peer ID to the peer you are swapping with, chain analysis entities could purchase this information from, as an example, a high-volume market maker that interacts with the protocol. Or they might find create a market for that information.

I surely agree that the peer ID should be recorded and kept constant during one swap. These are just my thoughts about adversarial cases if peer IDs are used for reputation or are constant across swaps.

**Comment by dimalinux** [comment]
> I don't think a non-random/constant peer ID could be used for reputation or history without impacting privacy. If the peer ID isn't random on every swap it could allow analysis entities to easily connect multiple trades (e.g., multiple XMR to ETH swaps to fresh addresses) to the same user and then de-anonymize them and the Ethereum addresses associated.

Alice or Bob can change their peer ID every time they restart `swapd`, and we can possibly even make that easier to do. My concern is about usability, given the constraints of a multi-chain swap. Alice risks losing some gas, when she takes an offer, if Bob doesn't complete the swap. If the percentage of bad Bobs on the network becomes too high, she may have good reason to seek out a reputable Bob. While Bob can chose to change his peer ID frequently, some Bobs that want a higher volume of swaps may chose to keep their peer ID longer and build reputation, even though doing so will absolutely degrade their privacy. ... that was my thoughts on the matter at least.

This issue is only about recording information, that is already known at swap time, in the user's local-only history of past swaps.

**Comment by dimalinux** [comment]
This will get closed as part of https://github.com/AthanorLabs/atomic-swap/pull/366, which adds the peer ID to the swap Info so Bob knows the peerID of Alice when he wants to connect to her for relay help.
