### ISSUE TITLE
feature to list all relayers and their requested fee

### ISSUE THREAD

**Issue by dimalinux** [AthanorLabs/atomic-swap#324]
This issue is to implement all the needed backend support for swapcli to be able to list relayers with their request fee.

**Comment by dimalinux** [comment]
With https://github.com/AthanorLabs/atomic-swap/pull/342 this can be done using:
```
./bin/swapcli discover --provides relayer
```
We could just update the documentation on the `--provides` flag to mention it, unless we want something more sophisticated.

**Comment by noot** [comment]
going to close this for now, as all relayers are using the same fee (and can be discovered w the above)
