### ISSUE TITLE
implement relayer/metatx support for swap contract `claim` function

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#33]
currently, Bob needs to have some ETH to pay for gas when calling `Claim()` to get his ETH. this is a pretty old ETH problem (eg. I have DAI but no ETH, so the DAI is trapped) - I'm sure there is likely some existing solution to this, just need to explore what's out there.

**Comment by alxs** [comment]
I'm surprised I can't actually find any real docs on this, but Tornado.Cash has [relayers](https://github.com/tornadocash/tornado-relayer) that submit the transactions for you and take a cut on the withdrawals - with some logic guaranteeing that the right relayer claims it or something. This should be straightforward to implement in our case.

I doubt there's really a better approach as of now. [Account abstraction](https://eips.ethereum.org/EIPS/eip-2938) is meant to solve the issue in the longer term.

**Comment by noot** [comment]
thanks for looking into this :D yeah, perhaps some sort of relayer scheme could work, we can look into how exactly it works. it would be nice to keep it trustless as well, I'm not sure how trustless the relayer scheme is.

**Comment by noot** [comment]
also, looks like EIP-3074 will solve this :)

**Comment by Crypt0-Bear** [comment]
This looks like a promising workaround until then

https://opengsn.org/

here is an implementation 
https://docs.opengsn.org/javascript-client/tutorial.html#converting-a-contract-to-support-gsn


It relies on a trusted sender but we could make it an open bounty time situation that when relaying is enabled anyone who sends the event to Bob gets paid a "relayers" fee. This still gives fallback for Bob to finalize the withdraw himself in the event that there is nobody else left.
