### ISSUE TITLE
remove address field from `NotifyXMRLock`

### ISSUE THREAD

**Issue by noot** [AthanorLabs/atomic-swap#335]
we can probably remove the `address` field, as each party can calculate the xmr lock address independently after the `SendKeysMessage` exchange.

**Comment by dimalinux** [comment]
If we can remove the `address` field from `NotifyXMRLock`, can't we go one step further and eliminate the `NotifyXMRLock` message all together? We'd just monitor the AB view wallet until it has the required amount of funds with 10 confirmations. Just a thought. Removing the address is probably a good first step regardless.
