### ISSUE TITLE
Question: stagenet environment?

### ISSUE THREAD

**Issue by NotGovernor** [AthanorLabs/atomic-swap#466]
This is exciting!

Question:
The docs at this location:  
[https://github.com/AthanorLabs/atomic-swap/blob/v0.2.1/docs/mainnet.md](https://github.com/AthanorLabs/atomic-swap/blob/v0.2.1/docs/mainnet.md)  

Say to start it with the stagenet environment:

`./bin/swapd --env stagenet --eth-endpoint MAINNET\_ENDPOINT --relayer`

Is that correct?

**Comment by dimalinux** [comment]
No, that's a mistake. We'll fix it.

**Comment by NotGovernor** [comment]
Awesome thanks!

**Comment by noot** [comment]
@NotGovernor sorry, this was fixed on master, but seems to not have made it into the release. will fix!

**Comment by noot** [comment]
closing as I've updated the v0.2.1 release notes and tagged a v0.2.2 release as well.
