### ISSUE TITLE
Questions: Relayer

### ISSUE THREAD

**Issue by NotGovernor** [AthanorLabs/atomic-swap#468]
I have a relay up with the eth address funded. Is there anything else needed? Do I need to forward any ports or list the relay anywhere? Or is this all automatic for makers and takers? I RTFM'd but didnt see anything on this stuff.

Thanks!

**Comment by dimalinux** [comment]
@NotGovernor You don't need to forward any ports, it is all automatic. You see how many relayers are on the network using this command. Note this command only shows peers, so you won't see the `swapd` instance being queried if that `swapd` instance is a realayer. I see 6 relayers on the network.
```text
 ./bin/swapcli discover  --provides relayer
```

**Comment by NotGovernor** [comment]
Excellent. I see 5, assuming 1 less because I'm querying a relayer.

Awesome!!! Well done all!
