### ISSUE TITLE
No offers?

### ISSUE THREAD

**Issue by hoonkai** [AthanorLabs/atomic-swap#510]
Hi I'm testing out the `swapcli` tool on mainnet and noticed there's no offer at all:

```
./bin/swapcli discover --provides XMR --search-time 3 --swapd-port 5000

[none]
```

Is this the expected output? Is there no market maker at all?

**Comment by hoonkai** [comment]
I see. But what alternative tools are there?

I'm trying to run it using mainnet endpoints to see that offer:

`./bin/swapd --eth-endpoint https://alchemyapi.io/ --monerod-host monero.ddns.net --monerod-port 18089`

But I keep getting this error:

`FATAL	cmd	swapd/main.go:228	invalid character '<' looking for beginning of value`

Do you know have an idea of what might be wrong?

**Comment by noot** [comment]
@hoonkai sounds like the eth endpoint you're using `alchemyapi.io` isn't returning an expected response, and the swap program can't decode it. see curl:
```
$ curl https://alchemyapi.io/
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
```

try another endpoint!

**Comment by hoonkai** [comment]
Thank you!
